apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-cms
  annotations:
    monokle.io/suppress.KBP001: false positive
  labels:
    monokle.io/demo: vanilla-blue-cms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-cms
  template:
    metadata:
      labels:
        app: blue-cms
    spec:
      containers:
        - name: blue-cms
          image: blue-cms:latest
          ports:
            - name: http-web
              containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsUser: 10001
            runAsGroup: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: blue-cms
  labels:
    monokle.io/demo: vanilla-blue-cms
spec:
  selector:
    app: blue-INCORRECT_REFERENCE
  ports:
    - name: http-web
      protocol: TCP
      port: 2
      targetPort: 8080
